import { SessionProvider } from "./auth-provider";
import "~/styles/globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className="flex h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
          {children}
        </body>
      </SessionProvider>
    </html>
  );
}

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [
    {
      rel: "icon",
      url: "/favicon.ico",
    },
  ],
};
